name: prepare-ios-build
description: Action to prepare environment for ios build

runs:
  using: composite
  steps:
    - name: ci/prepare-mobile-build
      uses: ./.github/actions/prepare-mobile-build

    - name: ci/install-pods-dependencies
      shell: bash
      run: |
        echo "::group::install-pods-dependencies"
        npm run ios-gems
        npm run pod-install
        echo "::endgroup::"

    - name: Cache Pods
      uses: actions/cache@0c45773b623bea8c8e75f6c82b208c3cf94ea4f9 # v4.0.2
      with:
        path: Pods
        key: ${{ runner.os }}-pods-${{ hashFiles('**/Podfile.lock') }}
        restore-keys: |
          ${{ runner.os }}-pods-
