---
name: ci
on:
  push:
    branches:
      - main
      - 'release*'
  pull_request:

env:
  NODE_VERSION: 20.13.1
  TERM: xterm

jobs:
  test:
    runs-on: ubuntu-22.04
    steps:
      - name: ci/checkout-repo
        uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1
      - name: ci/test
        uses: ./.github/actions/test
