name: Detox E2E Tests Release

on:
  push:
    branches:
      - release-*

jobs:
  update-initial-status:
    runs-on: ubuntu-22.04
    steps:
      - uses: mattermost/actions/delivery/update-commit-status@main
        env:
          GITHUB_TOKEN: ${{ github.token }}
        with:
          repository_full_name: ${{ github.repository }}
          commit_sha: ${{ github.sha }}
          context: e2e/detox-tests
          description: Detox tests for mattermost mobile app have started ...
          status: pending

  run-ios-tests-on-release:
    name: iOS Mobile Tests on Release
    uses: ./.github/workflows/e2e-detox-template.yml
    if: ${{ github.event_name == 'push' && startsWith(github.ref, 'refs/heads/release-') }}
    with:
      run-ios-tests: true
      run-android-tests: false
      run-type: "RELEASE"
      MOBILE_VERSION: ${{ github.ref }}
    secrets: inherit

  update-final-status:
    runs-on: ubuntu-22.04
    needs:
      - run-ios-tests-on-release
    steps:
      - uses: mattermost/actions/delivery/update-commit-status@main
        env:
          GITHUB_TOKEN: ${{ github.token }}
        with:
          repository_full_name: ${{ github.repository }}
          commit_sha: ${{ github.sha }}
          context: e2e/detox-tests
          description: Completed with ${{ needs.run-ios-tests-on-release.outputs.FAILURES }} failures
          status: ${{ needs.run-ios-tests-on-release.outputs.STATUS }}
          target_url: ${{ needs.run-ios-tests-on-release.outputs.TARGET_URL }}
