---
name: github-release
on:
  push:
    tags:
      - v[0-9]+.[0-9]+.[0-9]+*

jobs:
  test:
    runs-on: ubuntu-22.04
    steps:
      - name: ci/checkout-repo
        uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1
      - name: ci/test
        uses: ./.github/actions/test

  build-ios-unsigned:
    runs-on: macos-14-large
    needs:
      - test
    steps:
      - name: ci/checkout-repo
        uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1

      - name: ci/prepare-ios-build
        uses: ./.github/actions/prepare-ios-build

      - name: ci/output-ssh-private-key
        shell: bash
        run: |
          SSH_KEY_PATH=~/.ssh/id_ed25519
          mkdir -p ~/.ssh
          echo -e '${{ secrets.MM_MOBILE_PRIVATE_DEPLOY_KEY }}' > ${SSH_KEY_PATH}
          chmod 0600 ${SSH_KEY_PATH}
          ssh-keygen -y -f ${SSH_KEY_PATH} > ${SSH_KEY_PATH}.pub

      - name: ci/build-ios-unsigned
        env:
          TAG: "${{ github.ref_name }}"
          GITHUB_TOKEN: "${{ secrets.MM_MOBILE_GITHUB_TOKEN }}"
        run: bundle exec fastlane ios unsigned
        working-directory: ./fastlane

      - name: ci/upload-ios-unsigned
        uses: actions/upload-artifact@5d5d22a31266ced268874388b861e4b58bb5c2f3 # v4.3.1
        with:
          path: Mattermost-unsigned.ipa
          name: Mattermost-unsigned.ipa

  build-android-unsigned:
    runs-on: ubuntu-22.04
    needs:
      - test
    steps:
      - name: ci/checkout-repo
        uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1

      - name: ci/prepare-android-build
        uses: ./.github/actions/prepare-android-build
        with:
          sign: false

      - name: ci/build-android-beta
        env:
          TAG: "${{ github.ref_name }}"
          GITHUB_TOKEN: "${{ secrets.MM_MOBILE_GITHUB_TOKEN }}"
        run: bundle exec fastlane android unsigned
        working-directory: ./fastlane

      - name: ci/upload-android-unsigned-build
        uses: actions/upload-artifact@5d5d22a31266ced268874388b861e4b58bb5c2f3 # v4.3.1
        with:
          path: Mattermost-unsigned.apk
          name: Mattermost-unsigned.apk

  release:
    runs-on: ubuntu-22.04
    needs:
      - build-ios-unsigned
      - build-android-unsigned
    steps:
      - name: ci/checkout-repo
        uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1

      - uses: ruby/setup-ruby@22fdc77bf4148f810455b226c90fb81b5cbc00a7 # v1.171.0

      - name: release/setup-fastlane-dependencies
        run: bundle install
        working-directory: ./fastlane

      - name: ci/download-artifacts
        uses: actions/download-artifact@9bc31d5ccc31df68ecc42ccf4149144866c47d8a # v3.0.2

      - name: release/create-github-release
        env:
          GITHUB_TOKEN: "${{ secrets.MM_MOBILE_GITHUB_TOKEN }}"
        run: bundle exec fastlane github
        working-directory: ./fastlane
